"""Prepare, validate, and package VFX Texture Lab Windows releases."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tomllib
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = PROJECT_ROOT / "pyproject.toml"
CHANGELOG = PROJECT_ROOT / "CHANGELOG.md"
PACKAGE_INIT = PROJECT_ROOT / "vfx_texture_lab" / "__init__.py"
APP_DIRECTORY_NAME = "VFX Texture Lab"


@dataclass(frozen=True, slots=True)
class ReleaseMetadata:
    version: str
    windows_version: str
    tag: str
    asset_stem: str
    portable_filename: str
    installer_filename: str
    checksum_filename: str
    artifact_name: str


def read_project_version() -> str:
    data = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    version = str(data["project"]["version"]).strip()
    init_text = PACKAGE_INIT.read_text(encoding="utf-8")
    match = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', init_text, re.MULTILINE)
    if not match:
        raise RuntimeError("Could not find __version__ in vfx_texture_lab/__init__.py")
    package_version = match.group(1)
    if package_version != version:
        raise RuntimeError(
            f"Version mismatch: pyproject.toml says {version}, package says {package_version}."
        )
    return version


def metadata() -> ReleaseMetadata:
    version = read_project_version()
    stem = f"VFXTextureLab-{version}-Windows-x64"
    win_version = ".".join(str(value) for value in numeric_version(version))
    return ReleaseMetadata(
        version=version,
        windows_version=win_version,
        tag=f"v{version}",
        asset_stem=stem,
        portable_filename=f"{stem}-Portable.zip",
        installer_filename=f"{stem}-Setup.exe",
        checksum_filename=f"{stem}-SHA256.txt",
        artifact_name=stem,
    )


def numeric_version(version: str) -> tuple[int, int, int, int]:
    values = [int(value) for value in re.findall(r"\d+", version)[:4]]
    return tuple((values + [0, 0, 0, 0])[:4])  # type: ignore[return-value]


def write_version_info(path: Path, version: str) -> None:
    file_version = numeric_version(version)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f'''# UTF-8\n# Generated by tools/windows_release.py. Do not edit by hand.\nVSVersionInfo(\n  ffi=FixedFileInfo(\n    filevers={file_version!r},\n    prodvers={file_version!r},\n    mask=0x3f,\n    flags=0x0,\n    OS=0x40004,\n    fileType=0x1,\n    subtype=0x0,\n    date=(0, 0),\n  ),\n  kids=[\n    StringFileInfo([\n      StringTable(\n        '040904B0',\n        [\n          StringStruct('CompanyName', 'VFX Texture Lab contributors'),\n          StringStruct('FileDescription', 'VFX Texture Lab'),\n          StringStruct('FileVersion', '{version}'),\n          StringStruct('InternalName', 'VFXTextureLab'),\n          StringStruct('LegalCopyright', 'Copyright (c) Matty Wyett-Simmonds and contributors'),\n          StringStruct('OriginalFilename', 'VFX Texture Lab.exe'),\n          StringStruct('ProductName', 'VFX Texture Lab'),\n          StringStruct('ProductVersion', '{version}'),\n        ],\n      )\n    ]),\n    VarFileInfo([VarStruct('Translation', [1033, 1200])]),\n  ],\n)\n''',
        encoding="utf-8",
    )


def changelog_notes(version: str) -> str:
    text = CHANGELOG.read_text(encoding="utf-8")
    pattern = re.compile(
        rf"^##\s+{re.escape(version)}(?:\s+[^\n]*)?\n(?P<body>.*?)(?=^##\s+|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(text)
    if not match:
        return f"Windows x64 build of VFX Texture Lab {version}.\n"
    heading_match = re.search(
        rf"^##\s+({re.escape(version)}[^\n]*)", text, re.MULTILINE
    )
    title = heading_match.group(1).strip() if heading_match else version
    return f"# {title}\n\n{match.group('body').strip()}\n"


def write_github_outputs(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8", newline="\n") as handle:
        for key, value in values.items():
            handle.write(f"{key}={value}\n")


def command_prepare(args: argparse.Namespace) -> int:
    info = metadata()
    write_version_info(Path(args.version_info), info.version)
    notes_path = Path(args.release_notes)
    notes_path.parent.mkdir(parents=True, exist_ok=True)
    notes_path.write_text(changelog_notes(info.version), encoding="utf-8")
    metadata_path = Path(args.metadata_json)
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.write_text(json.dumps(asdict(info), indent=2) + "\n", encoding="utf-8")
    if args.github_output:
        write_github_outputs(Path(args.github_output), asdict(info))
    print(json.dumps(asdict(info), indent=2))
    return 0


def _find_matching(root: Path, predicate) -> list[Path]:
    return sorted(path for path in root.rglob("*") if path.is_file() and predicate(path))


def command_verify(args: argparse.Namespace) -> int:
    dist = Path(args.dist).resolve()
    exe = dist / f"{APP_DIRECTORY_NAME}.exe"
    failures: list[str] = []
    if not exe.is_file():
        failures.append(f"Missing executable: {exe}")
    if not (dist / "_internal").is_dir():
        failures.append(f"Missing PyInstaller _internal directory: {dist / '_internal'}")

    required_names = {
        "preview_3d.wgsl",
        "preview_3d_post.wgsl",
        "preview_3d_bloom.wgsl",
        "cayley_interior.npz",
        "chalk_quarry_sunset.npz",
        "overcast_soil.npz",
        "studio_small_02.npz",
        "qwindows.dll",
    }
    all_files = _find_matching(dist, lambda _path: True)
    found_names = {path.name.lower() for path in all_files}
    for name in sorted(required_names):
        if name.lower() not in found_names:
            failures.append(f"Missing required packaged file: {name}")

    shader_count = sum(path.suffix.lower() == ".wgsl" for path in all_files)
    if shader_count < 100:
        failures.append(f"Only {shader_count} WGSL files were found in the frozen build.")

    wgpu_dlls = [
        path for path in all_files
        if path.suffix.lower() == ".dll" and "wgpu" in path.name.lower()
    ]
    if not wgpu_dlls:
        failures.append("No wgpu-native DLL was found in the frozen build.")

    native_simplification_files = [
        path for path in all_files
        if path.suffix.lower() in {".pyd", ".dll"}
        and (
            "fast_simplification" in path.as_posix().lower()
            or "simplif" in path.name.lower()
        )
    ]
    if not native_simplification_files:
        failures.append("No fast-simplification native extension was found in the frozen build.")

    native_xatlas_files = [
        path for path in all_files
        if path.suffix.lower() in {".pyd", ".dll"}
        and "xatlas" in path.as_posix().lower()
    ]
    if not native_xatlas_files:
        failures.append("No xatlas native extension was found in the frozen build.")

    native_embreex_files = [
        path for path in all_files
        if path.suffix.lower() in {".pyd", ".dll"}
        and ("embreex" in path.as_posix().lower() or "embree" in path.name.lower())
    ]
    if not native_embreex_files:
        failures.append("No embreex/Embree native library was found in the frozen build.")

    if failures:
        for failure in failures:
            print(f"ERROR: {failure}", file=sys.stderr)
        return 1

    smoke_json = Path(args.smoke_json).resolve()
    smoke_json.parent.mkdir(parents=True, exist_ok=True)
    environment = dict(os.environ)
    environment.setdefault("QT_QPA_PLATFORM", "offscreen")
    result = subprocess.run(
        [str(exe), "--package-smoke-test", "--require-frozen", "--json", str(smoke_json)],
        cwd=dist,
        env=environment,
        timeout=args.timeout,
        check=False,
    )
    if result.returncode != 0:
        print(f"ERROR: Frozen executable smoke test returned {result.returncode}.", file=sys.stderr)
        if smoke_json.is_file():
            print(smoke_json.read_text(encoding="utf-8"), file=sys.stderr)
        return result.returncode or 1
    if not smoke_json.is_file():
        print("ERROR: Frozen executable did not write its smoke-test report.", file=sys.stderr)
        return 1
    report = json.loads(smoke_json.read_text(encoding="utf-8"))
    if not report.get("ok"):
        print(json.dumps(report, indent=2), file=sys.stderr)
        return 1
    print(json.dumps(report, indent=2))
    return 0


def _zip_directory(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(source.rglob("*")):
            if path.is_file():
                archive.write(path, Path(APP_DIRECTORY_NAME) / path.relative_to(source))


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def command_package(args: argparse.Namespace) -> int:
    info = metadata()
    dist = Path(args.dist).resolve()
    installer = Path(args.installer).resolve()
    release_dir = Path(args.release_dir).resolve()
    release_dir.mkdir(parents=True, exist_ok=True)
    if not (dist / f"{APP_DIRECTORY_NAME}.exe").is_file():
        raise FileNotFoundError(f"Frozen application directory is incomplete: {dist}")
    if not installer.is_file():
        raise FileNotFoundError(f"Inno Setup did not produce the installer: {installer}")

    portable = release_dir / info.portable_filename
    target_installer = release_dir / info.installer_filename
    if installer != target_installer:
        shutil.copy2(installer, target_installer)
    _zip_directory(dist, portable)

    checksum_path = release_dir / info.checksum_filename
    assets = (portable, target_installer)
    checksum_path.write_text(
        "".join(f"{_sha256(path)}  {path.name}\n" for path in assets),
        encoding="utf-8",
    )
    print(json.dumps({"assets": [str(path) for path in (*assets, checksum_path)]}, indent=2))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    metadata_parser = subparsers.add_parser("metadata", help="Print release metadata as JSON.")
    metadata_parser.set_defaults(func=lambda _args: (print(json.dumps(asdict(metadata()), indent=2)) or 0))

    prepare = subparsers.add_parser("prepare", help="Generate version metadata and release notes.")
    prepare.add_argument("--version-info", required=True)
    prepare.add_argument("--release-notes", required=True)
    prepare.add_argument("--metadata-json", required=True)
    prepare.add_argument("--github-output")
    prepare.set_defaults(func=command_prepare)

    verify = subparsers.add_parser("verify", help="Validate and run the frozen application.")
    verify.add_argument("--dist", required=True)
    verify.add_argument("--smoke-json", required=True)
    verify.add_argument("--timeout", type=int, default=180)
    verify.set_defaults(func=command_verify)

    package = subparsers.add_parser("package", help="Create portable ZIP and checksums.")
    package.add_argument("--dist", required=True)
    package.add_argument("--installer", required=True)
    package.add_argument("--release-dir", required=True)
    package.set_defaults(func=command_package)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
